"""Canonical, point-in-time-correct event schema for AutoCrypt.

This module is the load-bearing contract for the whole project. Every downstream
phase (backtest, attribution, paper, live) reads these records. Read the timestamp
discipline below before changing anything.

──────────────────────────────────────────────────────────────────────────────
TIMESTAMP DISCIPLINE (no look-ahead — this is the #1 way the backtest gets faked)
──────────────────────────────────────────────────────────────────────────────
Every record carries THREE distinct times. Confusing them is a bug:

  • event_time   — VALID TIME: when the fact became true *on-chain*.
                   - Swap / pool-created / liquidity-change → the block time of the tx.
                   - OHLCV bar → the bar's CLOSE time (a bar is not "true" until it closes).
                   - Holder / token-meta snapshot → the chain state ("as-of") time it reflects.

  • knowable_at  — KNOWN TIME: the earliest wall-clock time our system *could have*
                   known this fact. ALWAYS >= event_time. This is the ONLY time the
                   backtest / attribution model may gate on. A record is visible at
                   decision time T iff `knowable_at <= T`.
                     - tx events:      knowable_at = event_time + ingest latency
                     - OHLCV bar:      knowable_at = close_time + ingest latency  (NOT open_time!)
                     - snapshot:       knowable_at = as_of_time + compute/poll latency

  • observed_at  — AUDIT ONLY: the wall-clock time we actually fetched/received it.
                   For live ingestion observed_at ≈ knowable_at; for BACKFILL observed_at
                   is "now" (months after the fact). **observed_at must NEVER feed a
                   decision.** Backfill reconstructs knowable_at from event_time + an
                   assumed latency; it does not use fetch time. See `knowable_at_for_*`.

If you ever find a query that joins on observed_at to make a signal/decision, that is a
look-ahead bug — treat it as a Sev-1 against the entire backtest's validity.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timedelta
from decimal import Decimal
from enum import Enum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_VERSION = "1.0"


# ──────────────────────────────────────────────────────────────────────────────
# Enums
# ──────────────────────────────────────────────────────────────────────────────
class Chain(str, Enum):
    solana = "solana"
    base = "base"  # pre-committed fallback (Project_spec §3); not used in Phase 1


class EventType(str, Enum):
    pool_created = "pool_created"
    swap = "swap"
    liquidity_change = "liquidity_change"
    ohlcv_bar = "ohlcv_bar"
    holder_snapshot = "holder_snapshot"
    token_meta = "token_meta"
    wallet_event = "wallet_event"


class Source(str, Enum):
    """Which provider/adapter produced the record (provenance + cross-check)."""

    dexpaprika = "dexpaprika"
    geckoterminal = "geckoterminal"
    bitquery = "bitquery"
    flipside = "flipside"
    dune = "dune"
    birdeye = "birdeye"
    solana_rpc = "solana_rpc"
    synthetic = "synthetic"  # generated by tests/fixtures


class Commitment(str, Enum):
    """Solana commitment at knowable_at. `processed` can still be rolled back —
    a consumer acting on it accepts reorg risk. `backfill` = reconstructed history."""

    processed = "processed"
    confirmed = "confirmed"
    finalized = "finalized"
    backfill = "backfill"


class TradeSide(str, Enum):
    """Side w.r.t. the BASE (the low-cap token), not the quote."""

    buy = "buy"  # base token acquired (quote spent)
    sell = "sell"  # base token disposed (quote received)


class LiquiditySide(str, Enum):
    add = "add"
    remove = "remove"


class WalletAction(str, Enum):
    buy = "buy"
    sell = "sell"
    add_liquidity = "add_liquidity"
    remove_liquidity = "remove_liquidity"
    create_pool = "create_pool"
    transfer = "transfer"


class AuthorityStatus(str, Enum):
    """Mint/freeze authority status — a core rug-filter input (Project_spec §4.4)."""

    present = "present"  # authority exists → can mint/freeze (risk)
    revoked = "revoked"  # authority renounced/null (safer)
    unknown = "unknown"


# ──────────────────────────────────────────────────────────────────────────────
# Base envelope — shared by every record
# ──────────────────────────────────────────────────────────────────────────────
class BaseEvent(BaseModel):
    """Common envelope. Append-only: corrections/reorgs arrive as NEW rows with a
    higher `revision`, never as mutations of an existing row."""

    model_config = ConfigDict(extra="forbid", frozen=False)

    schema_version: str = SCHEMA_VERSION
    event_type: EventType
    chain: Chain = Chain.solana
    source: Source

    # ── the three times (see module docstring) ──
    event_time: datetime  # VALID time (tz-aware UTC)
    knowable_at: datetime  # KNOWN time — the no-look-ahead gate (>= event_time)
    observed_at: datetime | None = None  # AUDIT only — never gate decisions on this

    # ── on-chain ordering / provenance ──
    block_slot: int | None = None  # Solana slot; canonical monotonic order key
    source_ref: str | None = None  # provider's native id/cursor (provenance)
    ingest_run_id: str | None = None  # which ingestion job wrote this
    commitment: Commitment = Commitment.confirmed

    # ── correction / reorg bookkeeping (append-only) ──
    revision: int = 0
    superseded_by: str | None = None  # event_id of the row that replaces this one

    @property
    def ingest_latency_ms(self) -> float:
        """knowable_at - event_time, in milliseconds (transparency + QC)."""
        return (self.knowable_at - self.event_time).total_seconds() * 1000.0

    @model_validator(mode="after")
    def _check_times(self) -> BaseEvent:
        for name in ("event_time", "knowable_at"):
            ts = getattr(self, name)
            if ts.tzinfo is None:
                raise ValueError(f"{name} must be timezone-aware (UTC)")
        if self.knowable_at < self.event_time:
            raise ValueError(
                f"knowable_at ({self.knowable_at}) precedes event_time ({self.event_time}) "
                "— look-ahead violation"
            )
        return self

    def event_id(self) -> str:
        """Deterministic id from this record's natural key (for dedup). Overridden
        per-type; the default falls back to the whole envelope identity."""
        return _hash(
            self.chain.value,
            self.event_type.value,
            self.source.value,
            str(self.block_slot),
            self.event_time.isoformat(),
            str(self.revision),
        )


# ──────────────────────────────────────────────────────────────────────────────
# 1. Pool created (new launches / new pools)
# ──────────────────────────────────────────────────────────────────────────────
class PoolCreated(BaseEvent):
    event_type: Literal[EventType.pool_created] = EventType.pool_created

    pool_address: str  # AMM pool / pair address
    dex: str  # raydium | orca | meteora | pumpfun | ...
    program_id: str | None = None
    base_mint: str  # the low-cap token of interest
    quote_mint: str  # SOL / USDC / etc.
    base_decimals: int | None = None
    quote_decimals: int | None = None
    creator: str | None = None  # wallet that created the pool
    tx_signature: str | None = None

    # initial liquidity at creation (point-in-time)
    init_base_reserve: Decimal | None = None
    init_quote_reserve: Decimal | None = None
    init_liquidity_usd: Decimal | None = None
    init_price_usd: Decimal | None = None

    def event_id(self) -> str:
        return _hash(self.chain.value, "pool_created", self.pool_address, str(self.revision))


# ──────────────────────────────────────────────────────────────────────────────
# 2. Swap (DEX trade)
# ──────────────────────────────────────────────────────────────────────────────
class Swap(BaseEvent):
    event_type: Literal[EventType.swap] = EventType.swap

    pool_address: str
    dex: str | None = None
    base_mint: str
    quote_mint: str
    signer: str  # wallet that signed the swap (attribution subject)
    side: TradeSide

    # amounts: keep RAW integer base units AND ui Decimals; raw is the on-chain truth
    base_amount_raw: int | None = None
    quote_amount_raw: int | None = None
    base_amount: Decimal | None = None
    quote_amount: Decimal | None = None

    price_quote_per_base: Decimal | None = None
    price_usd: Decimal | None = None
    usd_price_source: str | None = None  # provenance of the USD valuation (lag risk!)
    amount_usd: Decimal | None = None

    tx_signature: str
    instruction_index: int | None = None  # disambiguates multiple swaps in one tx

    def event_id(self) -> str:
        return _hash(
            self.chain.value,
            "swap",
            self.tx_signature,
            str(self.instruction_index if self.instruction_index is not None else 0),
            str(self.revision),
        )


# ──────────────────────────────────────────────────────────────────────────────
# 3. Liquidity change (LP add/remove) — rug / liquidity-pull signal
# ──────────────────────────────────────────────────────────────────────────────
class LiquidityChange(BaseEvent):
    event_type: Literal[EventType.liquidity_change] = EventType.liquidity_change

    pool_address: str
    base_mint: str
    quote_mint: str
    wallet: str | None = None
    side: LiquiditySide

    base_amount: Decimal | None = None
    quote_amount: Decimal | None = None
    lp_token_delta: Decimal | None = None
    # resulting reserves AFTER the change (point-in-time pool state)
    base_reserve_after: Decimal | None = None
    quote_reserve_after: Decimal | None = None
    liquidity_usd_after: Decimal | None = None

    tx_signature: str
    instruction_index: int | None = None

    def event_id(self) -> str:
        return _hash(
            self.chain.value,
            "liquidity_change",
            self.tx_signature,
            str(self.instruction_index if self.instruction_index is not None else 0),
            str(self.revision),
        )


# ──────────────────────────────────────────────────────────────────────────────
# 4. OHLCV bar (the practical free-tier backfill unit)
# ──────────────────────────────────────────────────────────────────────────────
class OHLCVBar(BaseEvent):
    """A candle over [open_time, close_time). LOOK-AHEAD TRAP: a bar's high/low/close
    are unknown until the interval ends, so `event_time == close_time` and
    `knowable_at >= close_time`. Never stamp a bar at its open_time."""

    event_type: Literal[EventType.ohlcv_bar] = EventType.ohlcv_bar

    pool_address: str
    base_mint: str | None = None
    quote_mint: str | None = None
    interval: str  # "1m" | "5m" | "1h" | "1d" ...
    open_time: datetime
    close_time: datetime

    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume_base: Decimal | None = None
    volume_quote: Decimal | None = None
    volume_usd: Decimal | None = None
    trade_count: int | None = None
    currency: str = "usd"  # quote currency of the OHLC values

    @model_validator(mode="after")
    def _bar_times(self) -> OHLCVBar:
        if self.open_time.tzinfo is None or self.close_time.tzinfo is None:
            raise ValueError("open_time/close_time must be tz-aware (UTC)")
        if self.close_time <= self.open_time:
            raise ValueError("close_time must be after open_time")
        if self.event_time != self.close_time:
            raise ValueError("OHLCV event_time must equal close_time (no look-ahead)")
        return self

    def event_id(self) -> str:
        return _hash(
            self.chain.value,
            "ohlcv",
            self.pool_address,
            self.interval,
            self.open_time.isoformat(),
            str(self.revision),
        )


# ──────────────────────────────────────────────────────────────────────────────
# 5. Holder snapshot (polled state — a SAMPLE, do not interpolate)
# ──────────────────────────────────────────────────────────────────────────────
class HolderSnapshot(BaseEvent):
    """Holder distribution as of a chain slot. This is a POINT SAMPLE; the value
    between two snapshots is unknown — the backtest must step, not interpolate."""

    event_type: Literal[EventType.holder_snapshot] = EventType.holder_snapshot

    base_mint: str
    pool_address: str | None = None
    as_of_slot: int | None = None  # chain state this reflects (== block_slot)

    holder_count: int | None = None
    total_supply: Decimal | None = None
    circulating_supply: Decimal | None = None
    top10_pct: Decimal | None = None  # % of supply held by top 10 (concentration)
    top50_pct: Decimal | None = None
    creator_pct: Decimal | None = None  # % held by creator wallet
    lp_pct: Decimal | None = None  # % in LP

    def event_id(self) -> str:
        return _hash(
            self.chain.value,
            "holder_snapshot",
            self.base_mint,
            str(self.as_of_slot if self.as_of_slot is not None else self.event_time.isoformat()),
            str(self.revision),
        )


# ──────────────────────────────────────────────────────────────────────────────
# 6. Token metadata snapshot (rug-filter raw inputs — state can CHANGE over time)
# ──────────────────────────────────────────────────────────────────────────────
class TokenMeta(BaseEvent):
    """Time-stamped token metadata. Mint/freeze authority can be revoked and LP can be
    locked/burned AFTER launch, so this is a snapshot with valid-time semantics, not a
    static dimension. Always join as-of `knowable_at`."""

    event_type: Literal[EventType.token_meta] = EventType.token_meta

    base_mint: str
    symbol: str | None = None
    name: str | None = None
    decimals: int | None = None
    total_supply: Decimal | None = None

    mint_authority: AuthorityStatus = AuthorityStatus.unknown
    freeze_authority: AuthorityStatus = AuthorityStatus.unknown
    lp_locked: bool | None = None
    lp_burned: bool | None = None
    lp_lock_until: datetime | None = None
    is_honeypot: bool | None = None  # if a provider flags it; else computed later

    def event_id(self) -> str:
        return _hash(
            self.chain.value,
            "token_meta",
            self.base_mint,
            self.event_time.isoformat(),
            str(self.revision),
        )


# ──────────────────────────────────────────────────────────────────────────────
# 7. Wallet event (tracked-wallet activity projection)
# ──────────────────────────────────────────────────────────────────────────────
class WalletEvent(BaseEvent):
    """A wallet's action, linked to its underlying tx. The attribution LABEL ("is this
    a smart/leading wallet?") is intentionally NOT stored here — it is produced by the
    Phase 3 model and joined as-of `knowable_at`, so a label can never leak future
    information into a past decision."""

    event_type: Literal[EventType.wallet_event] = EventType.wallet_event

    wallet: str
    action: WalletAction
    base_mint: str | None = None
    quote_mint: str | None = None
    pool_address: str | None = None

    base_amount: Decimal | None = None
    quote_amount: Decimal | None = None
    amount_usd: Decimal | None = None

    tx_signature: str
    instruction_index: int | None = None
    # link back to the source event (swap/liquidity_change) this projects, if any
    linked_event_id: str | None = None

    def event_id(self) -> str:
        return _hash(
            self.chain.value,
            "wallet_event",
            self.wallet,
            self.tx_signature,
            str(self.instruction_index if self.instruction_index is not None else 0),
            self.action.value,
            str(self.revision),
        )


# Discriminated union for parsing/replay.
AnyEvent = Annotated[
    PoolCreated | Swap | LiquidityChange | OHLCVBar | HolderSnapshot | TokenMeta | WalletEvent,
    Field(discriminator="event_type"),
]


# ──────────────────────────────────────────────────────────────────────────────
# knowable_at helpers — the ONLY sanctioned way to reconstruct known-time on backfill
# ──────────────────────────────────────────────────────────────────────────────
def knowable_at_for_tx(block_time: datetime, latency: timedelta) -> datetime:
    """Tx-level events (swap/pool/liquidity): knowable once the block propagates."""
    return block_time + latency


def knowable_at_for_bar(close_time: datetime, latency: timedelta) -> datetime:
    """OHLCV bar: knowable only AFTER the bar closes (never at open)."""
    return close_time + latency


def knowable_at_for_snapshot(as_of_time: datetime, latency: timedelta) -> datetime:
    """Polled snapshot: knowable after the poll/compute completes against `as_of`."""
    return as_of_time + latency


def _hash(*parts: str) -> str:
    return hashlib.blake2b("\x1f".join(parts).encode("utf-8"), digest_size=16).hexdigest()
